query GetAnimebyQuery($query: String!, $page: Int) {
  getAnimebyQuery(query: $query, page: $page) {
    currentPage
    hasNextPage
    results {
      color
      cover
      currentEpisodeCount
      description
      genres
      id
      image
      popularity
      rating
      releaseDate
      status
      title {
        english
        native
        romaji
        userPreferred
      }
      totalEpisodes
      type
    }
  }
}

query GetAnimePlayerData($id: ID!) {
  getAnimebyId(id: $id) {
    description
    episodes {
      createdAt
      description
      id
      image
      number
      title
      url
    }
    zoroEpisodes {
      airDate
      createdAt
      description
      id
      image
      number
      title
      url
    }
  }
}

query GetAnimeStreamingData($anilistId: ID, $zoroId: ID) {
  animePlayerStreamingData(anilistId: $anilistId, zoroId: $zoroId) {
    intro {
      end
      start
    }
    outro {
      end
      start
    }
    headers {
      Referer
    }
    sources {
      quality
      url
    }
    subtitles {
      lang
      url
    }
    download
  }
}

query GetAnimePageData($id: ID!) {
  getAnimebyId(id: $id) {
    characters {
      id
      image
      name {
        full
        userPreferred
      }
      role
      voiceActors {
        id
        image
        language
        name {
          full
          userPreferred
        }
      }
    }
    cover
    currentEpisode
    description
    duration
    endDate {
      month
      year
      day
    }
    genres
    image
    rating
    recommendations {
      cover
      episodes
      id
      image
      rating
      status
      title {
        english
        native
        romaji
        userPreferred
      }
      type
    }
    releaseDate
    relations {
      cover
      episodes
      id
      image
      rating
      relationType
      status
      title {
        english
        native
        romaji
        userPreferred
      }
      type
    }
    season
    startDate {
      day
      month
      year
    }
    status
    studios
    subOrDub
    title {
      english
      romaji
      native
      userPreferred
    }
    trailer {
      id
    }
    type
    countryOfOrigin
    isAdult
    isLicensed
    synonyms
  }
}