query GetbyQuery($query: String!, $page: Int) {
  getAnybyQuery(query: $query, page: $page) {
    results {
      ... on Movie {
        backdrop_path
        id
        title
        overview
        poster_path
        media_type
        genre_ids
        vote_average
      }
      ... on TV {
        backdrop_path
        id
        name
        overview
        poster_path
        media_type
        genre_ids
        vote_average
      }
      ... on People {
        biography
        id
        name
        original_name
        media_type
        gender
        profile_path
        known_for_department
      }
    }
    currentPage
    hasNextPage
    total_pages
    total_results
  }
  getMoviebyQuery(query: $query, page: $page) {
    results {
      backdrop_path
      id
      title
      overview
      poster_path
      media_type
      genre_ids
      vote_average
    }
    currentPage
    hasNextPage
    total_pages
    total_results
  }
  getTvbyQuery(query: $query, page: $page) {
    results {
      backdrop_path
      id
      name
      overview
      poster_path
      media_type
      genre_ids
      vote_average
    }
    currentPage
    hasNextPage
    total_pages
    total_results
  }
  getpeoplebyQuery(query: $query, page: $page) {
    results {
      biography
      gender
      id
      media_type
      name
      original_name
      profile_path
      known_for_department
    }
    currentPage
    hasNextPage
    total_pages
    total_results
  }
}
