export const countriesList = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar (Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Réunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'U.S. Virgin Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'International',
]
export const categoriesList = [
  'Undefined',
  'General',
  'Music',
  'News',
  'Entertainment',
  'Religious',
  'Comedy',
  'Kids',
  'Lifestyle',
  'Series',
  'Movies',
  'Outdoor',
  'Business',
  'Documentary',
  'Auto',
  'Business;News',
  'Classic',
  'Shop',
  'Sports',
  'Legislative',
  'Culture',
  'Weather',
  'Animation',
  'Business;Legislative;News',
  'Relax',
  'Comedy;Series',
  'Culture;Documentary;Entertainment;General;Movies;Music',
  'Education',
  'Movies;Series',
  'Entertainment;General',
  'Cooking',
  'Family',
  'Documentary;Travel',
  'General;News',
  'Documentary;Education',
  'General;Religious',
  'Science',
  'Culture;Travel',
  'Kids;Music',
  'Travel',
  'Entertainment;Music',
  'Classic;Movies',
  'Classic;Music',
  'Culture;Education',
  'Culture;Music',
  'Education;General',
  'Animation;Kids',
  'Entertainment;Travel',
  'Family;Religious',
  'Family;General',
  'Kids;Religious',
  'Education;Outdoor;Relax',
  'Entertainment;Family',
  'Animation;Entertainment;Music;Religious',
  'Lifestyle;Shop',
  'Animation;Culture;Entertainment',
  'Entertainment;News',
  'Cooking;Shop',
  'Movies;News',
  'Culture;Sports',
  'Education;Kids',
  'Animation;Kids;Religious',
  'Music;News;Religious',
  'Culture;Education;Entertainment',
  'Culture;Entertainment;Music',
  'Animation;Kids;Music',
  'Documentary;Lifestyle',
  'Documentary;Science',
  'Movies;Music',
  'Culture;News',
  'Music;Religious',
  'Music;News',
  'Culture;General;Music;News',
  'Education;Religious',
  'Education;Outdoor',
  'Comedy;Movies',
  'Animation;Entertainment;Movies;Series',
  'Legislative;News',
  'Animation;Classic;Entertainment;Family;Movies',
  'Family;Movies',
  'Animation;Classic',
  'General;Music',
  'Culture;Religious',
  'General;Series',
  'Culture;Family',
  'Culture;General',
  'Family;Movies;Series',
  'Culture;Entertainment;News',
  'Culture;Science',
  'News;Religious',
  'News;Travel',
  'Documentary;News',
  'Auto;Entertainment',
  'Documentary;Entertainment;News',
  'Entertainment;Music;News',
  'Culture;Entertainment',
  'Entertainment;Family;News',
  'Business;Sports',
  'Entertainment;Series',
  'Entertainment;Shop',
  'Culture;Education;Lifestyle',
  'Animation;Classic;Kids',
  'Classic;Series',
  'Culture;Documentary;Education;Kids;Lifestyle;Science',
  'General;Kids',
  'Education;Science',
]
